start "COMS1" putty.exe -load "COMS1"
timeout /T 1 > nul
start "COMS3" putty.exe -load "COMS3"
timeout /T 1 > nul
start "COMS4" putty.exe -load "COMS4"
timeout /T 1 > nul
start "COMS5" putty.exe -load "COMS5"
timeout /T 1 > nul
start "COMS6" putty.exe -load "COMS6"
timeout /T 1 > nul
start "COMS7" putty.exe -load "COMS7"
timeout /T 1 > nul
start "COMS8" putty.exe -load "COMS8"
timeout /T 1 > nul
start "COMS9" putty.exe -load "COMS9"
timeout /T 1 > nul
start "COM10" putty.exe -load "COM10"
timeout /T 1 > nul
start "COM11" putty.exe -load "COM11"
timeout /T 1 > nul
start "COM12" putty.exe -load "COM12"
timeout /T 1 > nul
start "COM13" putty.exe -load "COM13"
timeout /T 1 > nul
start "COM14" putty.exe -load "COM14"
timeout /T 1 > nul
start "COM15" putty.exe -load "COM15"
timeout /T 1 > nul
start "COM16" putty.exe -load "COM16"
timeout /T 1 > nul
start "COM17" putty.exe -load "COM17"
timeout /T 1 > nul
start "COM18" putty.exe -load "COM18"
timeout /T 1 > nul
